#!/usr/bin/env bash
#
# package-toolchain.sh — assemble a self-contained, relocatable Android
# obfuscating toolchain from a built libHikari.so plus an LLVM 22 installation
# and an Android NDK.
#
# Result (default dist/hikari-android-toolchain):
#
#   bin/hikari-clang                       the 3-stage driver
#   bin/aarch64-linux-android24-clang      drop-in, target-injecting wrappers
#   bin/aarch64-linux-android24-clang++    (same names the NDK uses)
#   lib/libHikari.so                       the plugin
#   llvm/bin/opt                           LLVM 22 opt that loads the plugin
#   llvm/lib/libLLVM.so.22*                its runtime
#   README.md, examples/
#
# Usage:
#   HIKARI_NDK=/path/to/ndk LLVM_PREFIX=/usr/lib/llvm-22 \
#   HIKARI_PLUGIN=build/obfuscation/libHikari.so ./package-toolchain.sh
#
# Env:
#   HIKARI_NDK      Android NDK (required — its target wrappers are enumerated)
#   LLVM_PREFIX     LLVM 22 install prefix containing bin/opt (required)
#   HIKARI_PLUGIN   libHikari.so (required)
#   OUT_DIR         output root (default: <repo>/dist)
#   OBJCOPY/STRIP   optional, used to shrink opt/libLLVM when present

set -euo pipefail

die() { printf 'package-toolchain: %s\n' "$*" >&2; exit 1; }

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HIKARI_ROOT="$(cd "$SELF_DIR/../.." && pwd)"

HIKARI_NDK="${HIKARI_NDK:-}" || true
LLVM_PREFIX="${LLVM_PREFIX:-}" || true
HIKARI_PLUGIN="${HIKARI_PLUGIN:-}" || true
OUT_DIR="${OUT_DIR:-$HIKARI_ROOT/dist}"

[[ -n "$HIKARI_NDK" && -d "$HIKARI_NDK" ]] || die "set HIKARI_NDK to an Android NDK directory"
[[ -n "$LLVM_PREFIX" && -d "$LLVM_PREFIX" ]] || die "set LLVM_PREFIX to an LLVM 22 prefix (e.g. /usr/lib/llvm-22)"
[[ -n "$HIKARI_PLUGIN" && -f "$HIKARI_PLUGIN" ]] || die "set HIKARI_PLUGIN to the built libHikari.so"
[[ -x "$LLVM_PREFIX/bin/opt" ]] || die "$LLVM_PREFIX/bin/opt not found"

NAME="hikari-android-toolchain"
STAGE="$OUT_DIR/$NAME"
rm -rf "$STAGE"
mkdir -p "$STAGE/bin" "$STAGE/lib" "$STAGE/llvm/bin" "$STAGE/llvm/lib" "$STAGE/examples"

# --------------------------------------------------------------- binaries ---
cp "$HIKARI_PLUGIN" "$STAGE/lib/"
cp "$SELF_DIR/hikari-clang" "$STAGE/bin/hikari-clang"
chmod +x "$STAGE/bin/hikari-clang"

cp "$LLVM_PREFIX/bin/opt" "$STAGE/llvm/bin/opt"
chmod +x "$STAGE/llvm/bin/opt"

# opt's runtime (libLLVM + friends) so the archive works on clean machines.
copied_libs=0
while read -r lib; do
    [[ -f "$lib" ]] || continue
    cp -L "$lib" "$STAGE/llvm/lib/" && copied_libs=$((copied_libs + 1))
done < <(ldd "$LLVM_PREFIX/bin/opt" 2>/dev/null | awk '/=>/ {print $3}' | grep -E 'libLLVM|libz|libzstd|libtinfo' || true)
[[ "$copied_libs" -gt 0 ]] || echo "package-toolchain: warning: no LLVM runtime libs copied (opt may need system LLVM 22)" >&2

# Also keep the versioned soname the plugin links against, if we saw it.
for so in "$LLVM_PREFIX"/lib/libLLVM.so* /usr/lib/*/libLLVM.so*; do
    [[ -f "$so" ]] || continue
    base="$(basename "$so")"
    [[ -e "$STAGE/llvm/lib/$base" ]] || cp -L "$so" "$STAGE/llvm/lib/$base"
done 2>/dev/null || true

# ------------------------------------------------- per-target NDK wrappers ---
ndk_bin=""
for d in "$HIKARI_NDK"/toolchains/llvm/prebuilt/*/bin; do
    [[ -x "$d/clang" ]] && { ndk_bin="$d"; break; }
done
[[ -n "$ndk_bin" ]] || die "no toolchains/llvm/prebuilt/*/bin/clang under $HIKARI_NDK"

targets=0
for tc in "$ndk_bin"/*-linux-android*-clang; do
    [[ -e "$tc" ]] || continue
    base="$(basename "$tc")"                  # e.g. aarch64-linux-android24-clang
    targ="${base%-clang}"                     # aarch64-linux-android24
    for suffix in "" "++"; do
        gen="$STAGE/bin/${base}${suffix}"
        cat > "$gen" <<EOF
#!/usr/bin/env bash
# Generated by Hikari package-toolchain.sh — NDK target wrapper with obfuscation.
export HIKARI_TARGET="$targ"
exec "\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)/hikari-clang" --target=$targ "\$@"
EOF
        chmod +x "$gen"
        targets=$((targets + 1))
    done
done
[[ "$targets" -gt 0 ]] || die "no *-linux-android*-clang wrappers found in $ndk_bin"

# ---------------------------------------------------------------- extras ----
cp "$SELF_DIR/README.md" "$STAGE/README.md"
for s in "$HIKARI_ROOT"/samples/c/*.c; do
    [[ -f "$s" ]] && cp "$s" "$STAGE/examples/"
done
{
    echo "built: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "llvm-prefix: $LLVM_PREFIX"
    echo "llvm-version: $("$LLVM_PREFIX/bin/opt" --version 2>/dev/null | head -2 | tail -1)"
    echo "ndk: $HIKARI_NDK"
    echo "plugin: $(basename "$HIKARI_PLUGIN")"
} > "$STAGE/BUILD-INFO.txt"

( cd "$OUT_DIR" && tar czf "$NAME.tar.gz" "$NAME" )
echo "package-toolchain: wrote $OUT_DIR/$NAME.tar.gz"
du -sh "$OUT_DIR/$NAME.tar.gz"
